default: &default

  adapter: postgresql
  encoding: unicode
  password: Euco8785
  host: localhost
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RentMovies_development

test:
  <<: *default
  database: RentMovies_test

production:
  <<: *default
  database: RentMovies_production
  username: RentMovies
  password: <%= ENV["RENTMOVIES_DATABASE_PASSWORD"] %>